platform :ios, '16.0'

target 'InfraAdvisorMobile' do
  use_frameworks!

  pod 'DatadogCore', '~> 3.0'
  pod 'DatadogRUM', '~> 3.0'
  pod 'DatadogTrace', '~> 3.0'

  target 'InfraAdvisorMobileTests' do
    inherit! :search_paths
  end
end
