"""Chat attachment storage + audio transcription for multimodal input.

Uploaded images/audio land in Azure Blob Storage (container name from
AZURE_STORAGE_MEDIA_CONTAINER); callers get back a read-only SAS URL rather
than raw bytes, so attachments can flow through the request body, Redis
conversation history, and LangChain vision content without bloating any of
them — see docs/agent-guides/core-conventions.md's Redis session-memory note.

Audio is never sent to the chat LLM directly (cascade architecture): it is
transcribed here via an Azure OpenAI Whisper deployment, and the transcript
text is what agent.py folds into the effective query.
"""

import logging
import mimetypes
import os
import time
import uuid
import ipaddress
from datetime import datetime, timedelta, timezone
from typing import Literal
from urllib.parse import parse_qs, unquote, urlsplit

from urllib.request import HTTPRedirectHandler, Request, build_opener
from azure.storage.blob import (
    BlobSasPermissions,
    BlobServiceClient,
    ContentSettings,
    generate_blob_sas,
)
from ddtrace import tracer
from openai import AzureOpenAI
from pydantic import BaseModel

logger = logging.getLogger(__name__)

_ALLOWED_CONTENT_TYPES = {
    "image/jpeg": "image",
    "image/png": "image",
    "image/webp": "image",
    "audio/webm": "audio",
    "audio/wav": "audio",
    "audio/mpeg": "audio",
    "audio/ogg": "audio",
}
MAX_UPLOAD_BYTES = 10 * 1024 * 1024  # 10 MB


class UnsupportedMediaType(Exception):
    """Raised when the uploaded content-type is not on the allowlist."""


class MediaTooLarge(Exception):
    """Raised when the uploaded file exceeds MAX_UPLOAD_BYTES."""


class InvalidAttachmentReference(Exception):
    """Raised when a request references media outside our Blob boundary."""


class _RejectRedirects(HTTPRedirectHandler):
    """Do not let a validated Blob URL redirect the server to another host."""

    def redirect_request(self, req, fp, code, msg, headers, newurl):
        return None


class MediaAttachment(BaseModel):
    url: str
    kind: Literal["image", "audio"]
    mime_type: str
    size_bytes: int


def _media_container_name() -> str:
    return os.environ.get("AZURE_STORAGE_MEDIA_CONTAINER", "chat-media")


def _configured_blob_host() -> str:
    """Resolve the one Blob host attachments are allowed to reference.

    This is intentionally a local configuration parse, not DNS discovery or a
    network request. A malformed or incomplete storage configuration therefore
    fails closed before any attachment can reach an HTTP or model provider.
    """
    connection_string = os.environ.get("AZURE_STORAGE_CONNECTION_STRING", "")
    parts: dict[str, str] = {}
    for component in connection_string.split(";"):
        key, separator, value = component.partition("=")
        if separator:
            parts[key.strip().lower()] = value.strip()

    endpoint = os.environ.get("AZURE_STORAGE_BLOB_ENDPOINT") or parts.get("blobendpoint")
    if endpoint:
        host = urlsplit(endpoint).hostname
    else:
        account = parts.get("accountname")
        suffix = parts.get("endpointsuffix", "core.windows.net")
        host = f"{account}.blob.{suffix}" if account else None
    if not host:
        raise InvalidAttachmentReference("media storage host is not configured")
    return host.rstrip(".").lower()


def _is_public_host(host: str) -> bool:
    normalized = host.rstrip(".").lower()
    if normalized == "localhost" or normalized.endswith(".localhost"):
        return False
    try:
        return ipaddress.ip_address(normalized).is_global
    except ValueError:
        return True


def validate_attachment_reference(attachment: dict) -> dict:
    """Validate a client attachment at the final outbound-fetch boundary.

    Only HTTPS, read-only blob SAS URLs generated by this service's configured
    account/container and opaque ``<kind>/<uuid>`` object convention are
    accepted. Kind, MIME type, and declared size are validated together so
    clients cannot relabel an arbitrary URL before the agent or Whisper fetches
    it. The original dictionary is copied and normalized on success.
    """
    url = attachment.get("url")
    kind = attachment.get("kind")
    mime_type = str(attachment.get("mime_type") or "").split(";", 1)[0].strip().lower()
    size_bytes = attachment.get("size_bytes")
    if not isinstance(url, str) or not isinstance(kind, str):
        raise InvalidAttachmentReference("attachment fields are invalid")
    if isinstance(size_bytes, bool) or not isinstance(size_bytes, int) or not 0 < size_bytes <= MAX_UPLOAD_BYTES:
        raise InvalidAttachmentReference("attachment size is invalid")
    expected_kind = _ALLOWED_CONTENT_TYPES.get(mime_type)
    if expected_kind is None or expected_kind != kind:
        raise InvalidAttachmentReference("attachment kind and MIME type do not match")

    parsed = urlsplit(url)
    host = (parsed.hostname or "").rstrip(".").lower()
    if parsed.scheme != "https" or parsed.username or parsed.password or parsed.fragment:
        raise InvalidAttachmentReference("attachment URL is invalid")
    try:
        port = parsed.port
    except ValueError as exc:
        raise InvalidAttachmentReference("attachment URL port is invalid") from exc
    if port not in (None, 443) or not _is_public_host(host) or host != _configured_blob_host():
        raise InvalidAttachmentReference("attachment host is not allowed")

    path_parts = [unquote(part) for part in parsed.path.split("/") if part]
    container = _media_container_name()
    if len(path_parts) != 3 or path_parts[0] != container or path_parts[1] != kind:
        raise InvalidAttachmentReference("attachment container or kind path is invalid")
    blob_id = path_parts[2]
    if len(blob_id) != 32 or any(ch not in "0123456789abcdefABCDEF" for ch in blob_id):
        raise InvalidAttachmentReference("attachment object identifier is invalid")

    query = parse_qs(parsed.query, keep_blank_values=True, strict_parsing=True)
    required = {"sig", "se", "sp", "sr", "sv"}
    if not required.issubset(query) or any(len(query[key]) != 1 for key in required):
        raise InvalidAttachmentReference("attachment SAS contract is incomplete")
    if query["sp"] != ["r"] or query["sr"] != ["b"] or not query["sig"][0]:
        raise InvalidAttachmentReference("attachment SAS must be blob-scoped and read-only")

    return {
        "url": url,
        "kind": kind,
        "mime_type": mime_type,
        "size_bytes": size_bytes,
    }


def _sas_expiry_hours() -> int:
    return int(os.environ.get("MEDIA_SAS_EXPIRY_HOURS", "168"))


def get_blob_service_client() -> BlobServiceClient:
    conn_str = os.environ["AZURE_STORAGE_CONNECTION_STRING"]
    return BlobServiceClient.from_connection_string(conn_str)


def upload_media(
    file_bytes: bytes,
    filename: str,
    content_type: str,
    session_id: str,
) -> MediaAttachment:
    """Upload an image/audio file to Blob Storage and return a read-SAS URL.

    Raises UnsupportedMediaType / MediaTooLarge — callers translate these to
    415 / 413 HTTP responses.
    """
    # Browsers (MediaRecorder in particular) often send params after the type,
    # e.g. "audio/webm;codecs=opus" — match on the bare mime type.
    bare_content_type = content_type.split(";", 1)[0].strip().lower()
    kind = _ALLOWED_CONTENT_TYPES.get(bare_content_type)
    if kind is None:
        raise UnsupportedMediaType(content_type)
    if len(file_bytes) > MAX_UPLOAD_BYTES:
        raise MediaTooLarge(len(file_bytes))

    container_name = _media_container_name()
    # Object names are deliberately unlinkable to user-controlled metadata.
    # The original filename and chat session ID are needed by the HTTP/storage
    # workflow but must never become durable storage identifiers or telemetry.
    # Content-Type metadata is sufficient for serving the object back.
    blob_name = f"{kind}/{uuid.uuid4().hex}"

    with tracer.trace("azure.blob.upload", service="agent-api", resource=container_name) as span:
        span.set_tag("blob.container", container_name)
        span.set_tag("media.kind", kind)
        span.set_tag("blob.size_bytes", len(file_bytes))
        span.set_tag("blob.content_type", bare_content_type)

        service_client = get_blob_service_client()
        container_client = service_client.get_container_client(container_name)
        blob_client = container_client.upload_blob(
            name=blob_name,
            data=file_bytes,
            content_settings=ContentSettings(content_type=bare_content_type),
            overwrite=True,
        )

        account_name = service_client.account_name
        account_key = service_client.credential.account_key
        expiry = datetime.now(timezone.utc) + timedelta(hours=_sas_expiry_hours())
        sas_token = generate_blob_sas(
            account_name=account_name,
            container_name=container_name,
            blob_name=blob_name,
            account_key=account_key,
            permission=BlobSasPermissions(read=True),
            expiry=expiry,
        )
        url = f"{blob_client.url}?{sas_token}"

    return MediaAttachment(
        url=url,
        kind=kind,
        mime_type=bare_content_type,
        size_bytes=len(file_bytes),
    )


def download_media_bytes(url: str, expected_size: int) -> bytes:
    """Download an already-uploaded attachment's bytes from its SAS URL.

    Used only at the provider boundary by transcribe_audio. The URL and bytes
    are not returned to telemetry helpers.
    """
    # urllib is intentionally used instead of the globally auto-instrumented
    # httpx client. The parent transcription span records safe metadata, while
    # the credential-bearing SAS query string never becomes an HTTP span tag.
    request = Request(url, headers={"User-Agent": "infra-advisor-media/1.0"})
    opener = build_opener(_RejectRedirects())
    with opener.open(request, timeout=30.0) as response:
        content_length = response.headers.get("Content-Length")
        if content_length is not None and int(content_length) != expected_size:
            raise InvalidAttachmentReference("attachment size does not match Blob metadata")
        payload = response.read(MAX_UPLOAD_BYTES + 1)
    if len(payload) != expected_size:
        raise InvalidAttachmentReference("attachment size does not match the signed reference")
    return payload


def _whisper_client() -> AzureOpenAI:
    # Whisper lives on a SEPARATE Cognitive Services account/region from the
    # main chat/embedding deployments — whisper-001's "Standard" SKU isn't
    # offered in every region (confirmed absent in eastus via the Cognitive
    # Services models API), so it has its own account in a region that does
    # support it. See infra/bicep/modules/azure-openai.bicep.
    return AzureOpenAI(
        azure_endpoint=os.environ["AZURE_OPENAI_WHISPER_ENDPOINT"],
        api_key=os.environ["AZURE_OPENAI_WHISPER_API_KEY"],
        api_version="2025-01-01-preview",
    )


def transcribe_audio(url: str, mime_type: str, size_bytes: int) -> tuple[str, float]:
    """Download the SAS-URL'd audio blob and transcribe it via Azure OpenAI Whisper.

    Returns (transcript, duration_s). duration_s is a best-effort
    wall-clock measurement of the transcription call itself, not the audio's
    actual playback length — Whisper's response doesn't reliably include
    duration for every input format, and decoding the audio just to measure
    it isn't worth a new dependency for a demo feature. Raw audio bytes are
    kept local to this provider call and are never returned to telemetry code.
    """
    deployment = os.environ.get("AZURE_OPENAI_WHISPER_DEPLOYMENT", "whisper")
    ext = mimetypes.guess_extension(mime_type) or ".webm"

    audio_bytes = download_media_bytes(url, size_bytes)

    client = _whisper_client()
    start = time.monotonic()
    transcription = client.audio.transcriptions.create(
        model=deployment,
        file=(f"audio{ext}", audio_bytes, mime_type),
    )
    duration_s = time.monotonic() - start

    return transcription.text, duration_s
