<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>InfraAdvisor.Mobile.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/InfraAdvisor.Mobile.Core/InfraAdvisor.Mobile.Core.csproj" />
    <ProjectReference Include="../../src/InfraAdvisor.Mobile.Presentation/InfraAdvisor.Mobile.Presentation.csproj" />
  </ItemGroup>
</Project>
