org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true

infraAdvisorApiBaseUrl=https://infra-advisor-ai.kyletaylor.dev
datadogSite=US3
datadogEnv=demo
datadogService=infra-advisor-mobile-android
datadogRumApplicationId=37f46e3b-cfbb-432f-862e-118b97b8b696
datadogClientToken=pub71e6c404531eb97dfac1b10ad4c96489
datadogTraceSampleRate=100
